server {
    listen 80;

    # Redirect root (/) to another website
    location = / {
        return 307 $REDIRECT_URL;
    }

    # Disable caching for index.html
    location = /index.html {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Serve React app for all other routes
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }    
}