export const styles = {
    wrapper: {
        px: { sm: 3, xs: 1 },
        py: 3,
        width: '100%',
    },
    title: {
        fontSize: {
            xl: '28px',
            sm: '24px',
            xs: '20px',
        },
        lineHeight: {
            xl: '34px',
            sm: '28px',
            xs: '24px',
        },
        fontWeight: 600,
        mb: '8px',
        color: '#1a1a2e',
    },
    description: {
        fontSize: {
            xl: '16px',
            sm: '14px',
            xs: '13px',
        },
        lineHeight: {
            xl: '24px',
            sm: '20px',
            xs: '18px',
        },
        maxWidth: '710px',
        color: '#64748b',
    },
    cardTotalContainer: {
        backgroundColor: '#1e3a5f',
        borderRadius: '12px',
        px: { xs: '20px', xl: '24px' },
        py: '20px',
        width: { sm: '310px', xs: '100%' },
        mb: '24px',
        transition: 'transform 0.2s ease, box-shadow 0.2s ease',
        '&:hover': {
            transform: 'translateY(-2px)',
            boxShadow: '0px 8px 24px rgba(30, 58, 95, 0.25)',
        },
    },
    cardTotalAmount: {
        fontSize: { xl: '40px', xs: '32px' },
        color: '#FFFFFF',
        fontWeight: 700,
        lineHeight: 1.2,
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        mb: { xs: '12px', sm: '20px' },
        cursor: 'pointer',
    },
    cardTotalTitle: {
        fontSize: { sm: '13px', xs: '12px' },
        color: '#e2e8f0',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        fontWeight: 500,
    },
    cardTotalIcon: {
        color: '#e2e8f0',
        fontSize: { sm: '20px', xs: '16px' },
        opacity: 0.7,
    },
    chartContainer: {
        px: { sm: 3, xs: 2 },
        py: 3,
        borderRadius: '12px',
        width: '100%',
        maxWidth: '100%',
        border: '1px solid #e2e8f0',
        backgroundColor: '#ffffff',
        boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.08)',
    },
    chartHeaderContainer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        mb: 3,
    },
    chartSelect: {
        height: { sm: '40px', xs: '32px' },
        fontSize: '0.875rem',
        '& .MuiOutlinedInput-notchedOutline': {
            borderColor: '#e2e8f0',
        },
        '&:hover .MuiOutlinedInput-notchedOutline': {
            borderColor: '#cbd5e1',
        },
    },
    chartTooltip: {
        p: 2,
        backgroundColor: '#1a1a2e',
        color: 'white',
        borderRadius: 2,
        position: 'relative',
        '&::after': {
            content: '""',
            position: 'absolute',
            top: '100%',
            left: '50%',
            transform: 'translateX(-50%)',
            width: 0,
            height: 0,
            borderLeft: '6px solid transparent',
            borderRight: '6px solid transparent',
            borderTop: '6px solid #1a1a2e',
        },
    },
}
